### PR TITLE
Bashir has just finished the task of US500

### PR DESCRIPTION
**Pull request by bashir-hasanov**
Added code 1 first
Added code 2 second
Added code 3 last

### CODE REVIEW

**Review by YigitTolga — APPROVED** [review]

**Review by JuliaTkachenko26 — COMMENTED** [review]
Great code Bashir,keep coding!

**Review by bashir-hasanov — COMMENTED** [review]
Done

**Review by ghost — COMMENTED** [review]
good job bro!

**Review by MadinaDanaeva — APPROVED** [review]

**Review by JuliaTkachenko26 — COMMENTED** [review]
great cucumber code

**Pull request merged**
