### PR TITLE
Hello Word days

### PR DESCRIPTION
**Pull request by YigitTolga**
Guys Can you please review my code :D I need to approval for merge.

### CODE REVIEW

**Review by bashir-hasanov — APPROVED** [review]
All looks good. Reviewed and approved!

Regards,
Bashir

**Comment by vlajkousa** [comment]
Great job!

**Comment by MadinaDanaeva** [comment]
Great job!

**Review by MadinaDanaeva — APPROVED** [review]

**Comment by zizuasme33** [comment]
Reviewed

**Comment by YigitTolga** [comment]
Thank you guys

**Review by JuliaTkachenko26 — COMMENTED** [review]
Great code Tolga!

**Comment by tumacho-hub** [comment]
group project!

**Pull request merged**
