### PR TITLE
TC004part2 getting hungy!

### PR DESCRIPTION
**Pull request by vlajkousa**
coding makes me hungry

### CODE REVIEW

**Comment by vlajkousa** [comment]
Dinner is ready

**Comment by YigitTolga** [comment]
enjoy

**Review by bashir-hasanov — APPROVED** [review]
If you are hungry, you need to eat something! 
Approved your hunger!

**Comment by MadinaDanaeva** [comment]
Something, like pizza would be perfect :)

**Review by zizuasme33 — APPROVED** [review]
Checked

**Comment by tumacho-hub** [comment]
who is hungy!? lol

**Review by YigitTolga — APPROVED** [review]
approve

**Pull request merged**
