### PR TITLE
Zebib

### PR DESCRIPTION
**Pull request by zizuasme33**

### CODE REVIEW

**Review by YigitTolga — COMMENTED** [review]
Good work.

**Review by YigitTolga — APPROVED** [review]

**Review by MadinaDanaeva — APPROVED** [review]
Stay calm, keep coding 🥇

**Review by MadinaDanaeva — CHANGES_REQUESTED** [review]
zizu_ss@yahoo.com

**Review by MadinaDanaeva — APPROVED** [review]
Just playing around

**Review by YigitTolga — APPROVED** [review]
good changes :D 🗡️ 💯

**Pull request merged**
