### PR TITLE
Completed US500 TC002

### PR DESCRIPTION
**Pull request by tumacho-hub**
Finished creating cucumber framework

### CODE REVIEW

**Review by YigitTolga — APPROVED** [review]
good job

**Comment by tumacho-hub** [comment]
thanks!

**Comment by vlajkousa** [comment]
It is time for tomato framework!!!

**Review by YigitTolga — APPROVED** [review]

**Review by YigitTolga — APPROVED** [review]
aprroved Jorge, Tomorrow we are creating boot capm calender I will share with you

**Review by YigitTolga — APPROVED** [review]

**Comment by tumacho-hub** [comment]
copy!  are we having a meeting for it or you just creating it?

**Comment by YigitTolga** [comment]
tomorrow 10 am EST

**Comment by tumacho-hub** [comment]
> tomorrow 10 am EST

I will join around 10:15  I have to drop off my little man to camp.

**Comment by tumacho-hub** [comment]
closing again lol

**Pull request closed without merging**
